### ISSUE TITLE
VSC Paste breaks after certain actions when extension is enabled. 

### ISSUE THREAD

**Issue by dskzz** [jhasse/vscode-bracket-select#1]
I had this extension installed and if I did multi-cursor select or pop copilot out of the sidebar and a few other things paste would stop working.   Copy still worked and paste still worked outside of VSC.  

 I got this message when trying to paste in the output for window:
2024-01-08 14:34:03.807 [error] Illegal value for `line`: Error: Illegal value for `line`
    at m.t (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:961)
    at Object.lineAt (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:90)
    at editorHasClosingAt (c:\Users\dmzBC\.vscode\extensions\jomeinaster.bracket-peek-1.4.4\src\utils\closest-closing.js:44:42)
    at module.exports (c:\Users\dmzBC\.vscode\extensions\jomeinaster.bracket-peek-1.4.4\src\utils\closest-closing.js:13:7)
    at Object.provideHover (c:\Users\dmzBC\.vscode\extensions\jomeinaster.bracket-peek-1.4.4\src\extension.js:83:29)
    at provideHover (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:42378)
    at c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:68716
    at be.s (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:66141)
    at be.$provideHover (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:68703)
    at l.S (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10829)
    at l.Q (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10595)
    at l.M (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:9647)
    at l.L (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:8764)
    at f.value (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:7567)
    at n.y (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at o.fire (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
    at f.value (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:7903)
    at n.y (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at o.fire (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
    at MessagePortMain.<anonymous> (c:\Users\dmzBC\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:6183)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)

I disabled the extension the problem seemed to stop.  If you need more info or some testing lmk.

**Comment by dhananjaipai** [comment]
Does this issue still persist? I do not seem to have the same issue
